// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLogEntry = `-- name: CreateAuditLogEntry :one
INSERT INTO audit_log (workspace_id, actor_user_id, actor, action, target, at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, actor_user_id, action, target, at, created_at, actor
`

type CreateAuditLogEntryParams struct {
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	ActorUserID *uuid.UUID         `json:"actor_user_id"`
	Actor       string             `json:"actor"`
	Action      string             `json:"action"`
	Target      string             `json:"target"`
	At          pgtype.Timestamptz `json:"at"`
}

func (q *Queries) CreateAuditLogEntry(ctx context.Context, arg CreateAuditLogEntryParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLogEntry,
		arg.WorkspaceID,
		arg.ActorUserID,
		arg.Actor,
		arg.Action,
		arg.Target,
		arg.At,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ActorUserID,
		&i.Action,
		&i.Target,
		&i.At,
		&i.CreatedAt,
		&i.Actor,
	)
	return i, err
}

const deleteAuditLogEntry = `-- name: DeleteAuditLogEntry :execrows
DELETE FROM audit_log
WHERE id = $1 AND workspace_id = $2
`

type DeleteAuditLogEntryParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteAuditLogEntry(ctx context.Context, arg DeleteAuditLogEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAuditLogEntry, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAuditLogEntry = `-- name: GetAuditLogEntry :one
SELECT id, workspace_id, actor_user_id, action, target, at, created_at, actor FROM audit_log
WHERE id = $1 AND workspace_id = $2
`

type GetAuditLogEntryParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetAuditLogEntry(ctx context.Context, arg GetAuditLogEntryParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getAuditLogEntry, arg.ID, arg.WorkspaceID)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ActorUserID,
		&i.Action,
		&i.Target,
		&i.At,
		&i.CreatedAt,
		&i.Actor,
	)
	return i, err
}

const listAuditLogByWorkspace = `-- name: ListAuditLogByWorkspace :many
SELECT id, workspace_id, actor_user_id, action, target, at, created_at, actor FROM audit_log
WHERE workspace_id = $1
  AND (
      $2::timestamptz IS NULL
      OR (created_at, id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListAuditLogByWorkspaceParams struct {
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        *uuid.UUID         `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

func (q *Queries) ListAuditLogByWorkspace(ctx context.Context, arg ListAuditLogByWorkspaceParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogByWorkspace,
		arg.WorkspaceID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ActorUserID,
			&i.Action,
			&i.Target,
			&i.At,
			&i.CreatedAt,
			&i.Actor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuditLogEntry = `-- name: UpdateAuditLogEntry :one
UPDATE audit_log SET target = COALESCE($1, target)
WHERE id = $2 AND workspace_id = $3
RETURNING id, workspace_id, actor_user_id, action, target, at, created_at, actor
`

type UpdateAuditLogEntryParams struct {
	Target      *string   `json:"target"`
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateAuditLogEntry(ctx context.Context, arg UpdateAuditLogEntryParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, updateAuditLogEntry, arg.Target, arg.ID, arg.WorkspaceID)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ActorUserID,
		&i.Action,
		&i.Target,
		&i.At,
		&i.CreatedAt,
		&i.Actor,
	)
	return i, err
}
