// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_otp_verify_attempts.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOTPVerifyAttemptsByDestination = `-- name: CountOTPVerifyAttemptsByDestination :one
SELECT count(*) FROM auth_otp_verify_attempts
WHERE destination = $1
  AND created_at >= $2
`

type CountOTPVerifyAttemptsByDestinationParams struct {
	Destination string             `json:"destination"`
	Since       pgtype.Timestamptz `json:"since"`
}

func (q *Queries) CountOTPVerifyAttemptsByDestination(ctx context.Context, arg CountOTPVerifyAttemptsByDestinationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOTPVerifyAttemptsByDestination, arg.Destination, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOTPVerifyAttemptsByIP = `-- name: CountOTPVerifyAttemptsByIP :one
SELECT count(*) FROM auth_otp_verify_attempts
WHERE ip = $1
  AND ip <> ''
  AND created_at >= $2
`

type CountOTPVerifyAttemptsByIPParams struct {
	Ip    string             `json:"ip"`
	Since pgtype.Timestamptz `json:"since"`
}

func (q *Queries) CountOTPVerifyAttemptsByIP(ctx context.Context, arg CountOTPVerifyAttemptsByIPParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOTPVerifyAttemptsByIP, arg.Ip, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOTPVerifyAttempt = `-- name: CreateOTPVerifyAttempt :exec
INSERT INTO auth_otp_verify_attempts (destination, ip, created_at)
VALUES ($1, $2, $3)
`

type CreateOTPVerifyAttemptParams struct {
	Destination string             `json:"destination"`
	Ip          string             `json:"ip"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateOTPVerifyAttempt(ctx context.Context, arg CreateOTPVerifyAttemptParams) error {
	_, err := q.db.Exec(ctx, createOTPVerifyAttempt, arg.Destination, arg.Ip, arg.CreatedAt)
	return err
}

const deleteExpiredOTPVerifyAttempts = `-- name: DeleteExpiredOTPVerifyAttempts :execrows
DELETE FROM auth_otp_verify_attempts WHERE created_at < $1
`

func (q *Queries) DeleteExpiredOTPVerifyAttempts(ctx context.Context, before pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOTPVerifyAttempts, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
