// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_otps.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeAuthOTP = `-- name: ConsumeAuthOTP :execrows
UPDATE auth_otps SET consumed_at = $1
WHERE id = $2 AND consumed_at IS NULL
`

type ConsumeAuthOTPParams struct {
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	ID         uuid.UUID          `json:"id"`
}

func (q *Queries) ConsumeAuthOTP(ctx context.Context, arg ConsumeAuthOTPParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeAuthOTP, arg.ConsumedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countAuthOTPsByDestination = `-- name: CountAuthOTPsByDestination :one
SELECT count(*) FROM auth_otps
WHERE channel = $1
  AND destination = $2
  AND created_at >= $3
`

type CountAuthOTPsByDestinationParams struct {
	Channel     string             `json:"channel"`
	Destination string             `json:"destination"`
	Since       pgtype.Timestamptz `json:"since"`
}

func (q *Queries) CountAuthOTPsByDestination(ctx context.Context, arg CountAuthOTPsByDestinationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuthOTPsByDestination, arg.Channel, arg.Destination, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuthOTPsByIP = `-- name: CountAuthOTPsByIP :one
SELECT count(*) FROM auth_otps
WHERE request_ip = $1
  AND request_ip <> ''
  AND created_at >= $2
`

type CountAuthOTPsByIPParams struct {
	RequestIp string             `json:"request_ip"`
	Since     pgtype.Timestamptz `json:"since"`
}

func (q *Queries) CountAuthOTPsByIP(ctx context.Context, arg CountAuthOTPsByIPParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuthOTPsByIP, arg.RequestIp, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthOTP = `-- name: CreateAuthOTP :one
INSERT INTO auth_otps (channel, destination, code_hash, expires_at, request_ip, created_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, channel, destination, code_hash, expires_at, attempts, consumed_at, request_ip, created_at
`

type CreateAuthOTPParams struct {
	Channel     string             `json:"channel"`
	Destination string             `json:"destination"`
	CodeHash    string             `json:"code_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RequestIp   string             `json:"request_ip"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAuthOTP(ctx context.Context, arg CreateAuthOTPParams) (AuthOtp, error) {
	row := q.db.QueryRow(ctx, createAuthOTP,
		arg.Channel,
		arg.Destination,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.RequestIp,
		arg.CreatedAt,
	)
	var i AuthOtp
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.Destination,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.ConsumedAt,
		&i.RequestIp,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredAuthOTPs = `-- name: DeleteExpiredAuthOTPs :execrows
DELETE FROM auth_otps WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredAuthOTPs(ctx context.Context, before pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAuthOTPs, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLatestAuthOTP = `-- name: GetLatestAuthOTP :one
SELECT id, channel, destination, code_hash, expires_at, attempts, consumed_at, request_ip, created_at FROM auth_otps
WHERE channel = $1
  AND destination = $2
  AND consumed_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetLatestAuthOTPParams struct {
	Channel     string `json:"channel"`
	Destination string `json:"destination"`
}

func (q *Queries) GetLatestAuthOTP(ctx context.Context, arg GetLatestAuthOTPParams) (AuthOtp, error) {
	row := q.db.QueryRow(ctx, getLatestAuthOTP, arg.Channel, arg.Destination)
	var i AuthOtp
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.Destination,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.ConsumedAt,
		&i.RequestIp,
		&i.CreatedAt,
	)
	return i, err
}

const recordAuthOTPAttempt = `-- name: RecordAuthOTPAttempt :one
UPDATE auth_otps SET attempts = attempts + 1
WHERE id = $1
RETURNING attempts
`

func (q *Queries) RecordAuthOTPAttempt(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, recordAuthOTPAttempt, id)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}
