// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bot_jobs.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBotJob = `-- name: CreateBotJob :one
INSERT INTO bot_jobs (workspace_id, meeting_url, platform, scheduled_at, status, worker_id,
                      estimated_minutes, bot_name)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8)
RETURNING id, workspace_id, meeting_url, platform, scheduled_at, status, worker_id, minutes_used, consent_announced_at, error, created_at, estimated_minutes, bot_name
`

type CreateBotJobParams struct {
	WorkspaceID      uuid.UUID          `json:"workspace_id"`
	MeetingUrl       string             `json:"meeting_url"`
	Platform         string             `json:"platform"`
	ScheduledAt      pgtype.Timestamptz `json:"scheduled_at"`
	Status           string             `json:"status"`
	WorkerID         *string            `json:"worker_id"`
	EstimatedMinutes int32              `json:"estimated_minutes"`
	BotName          *string            `json:"bot_name"`
}

func (q *Queries) CreateBotJob(ctx context.Context, arg CreateBotJobParams) (BotJob, error) {
	row := q.db.QueryRow(ctx, createBotJob,
		arg.WorkspaceID,
		arg.MeetingUrl,
		arg.Platform,
		arg.ScheduledAt,
		arg.Status,
		arg.WorkerID,
		arg.EstimatedMinutes,
		arg.BotName,
	)
	var i BotJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.MeetingUrl,
		&i.Platform,
		&i.ScheduledAt,
		&i.Status,
		&i.WorkerID,
		&i.MinutesUsed,
		&i.ConsentAnnouncedAt,
		&i.Error,
		&i.CreatedAt,
		&i.EstimatedMinutes,
		&i.BotName,
	)
	return i, err
}

const deleteBotJob = `-- name: DeleteBotJob :execrows
DELETE FROM bot_jobs
WHERE id = $1 AND workspace_id = $2
`

type DeleteBotJobParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteBotJob(ctx context.Context, arg DeleteBotJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBotJob, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBotJob = `-- name: GetBotJob :one
SELECT id, workspace_id, meeting_url, platform, scheduled_at, status, worker_id, minutes_used, consent_announced_at, error, created_at, estimated_minutes, bot_name FROM bot_jobs
WHERE id = $1 AND workspace_id = $2
`

type GetBotJobParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetBotJob(ctx context.Context, arg GetBotJobParams) (BotJob, error) {
	row := q.db.QueryRow(ctx, getBotJob, arg.ID, arg.WorkspaceID)
	var i BotJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.MeetingUrl,
		&i.Platform,
		&i.ScheduledAt,
		&i.Status,
		&i.WorkerID,
		&i.MinutesUsed,
		&i.ConsentAnnouncedAt,
		&i.Error,
		&i.CreatedAt,
		&i.EstimatedMinutes,
		&i.BotName,
	)
	return i, err
}

const listBotJobsByWorkspace = `-- name: ListBotJobsByWorkspace :many
SELECT id, workspace_id, meeting_url, platform, scheduled_at, status, worker_id, minutes_used, consent_announced_at, error, created_at, estimated_minutes, bot_name FROM bot_jobs
WHERE workspace_id = $1
  AND (
      $2::timestamptz IS NULL
      OR (created_at, id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListBotJobsByWorkspaceParams struct {
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        *uuid.UUID         `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

func (q *Queries) ListBotJobsByWorkspace(ctx context.Context, arg ListBotJobsByWorkspaceParams) ([]BotJob, error) {
	rows, err := q.db.Query(ctx, listBotJobsByWorkspace,
		arg.WorkspaceID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BotJob{}
	for rows.Next() {
		var i BotJob
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.MeetingUrl,
			&i.Platform,
			&i.ScheduledAt,
			&i.Status,
			&i.WorkerID,
			&i.MinutesUsed,
			&i.ConsentAnnouncedAt,
			&i.Error,
			&i.CreatedAt,
			&i.EstimatedMinutes,
			&i.BotName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBotJob = `-- name: UpdateBotJob :one
UPDATE bot_jobs SET
    status = COALESCE($1, status),
    worker_id = COALESCE($2, worker_id),
    minutes_used = COALESCE($3, minutes_used),
    consent_announced_at = COALESCE($4, consent_announced_at),
    error = COALESCE($5, error)
WHERE id = $6 AND workspace_id = $7
RETURNING id, workspace_id, meeting_url, platform, scheduled_at, status, worker_id, minutes_used, consent_announced_at, error, created_at, estimated_minutes, bot_name
`

type UpdateBotJobParams struct {
	Status             *string            `json:"status"`
	WorkerID           *string            `json:"worker_id"`
	MinutesUsed        *int32             `json:"minutes_used"`
	ConsentAnnouncedAt pgtype.Timestamptz `json:"consent_announced_at"`
	Error              *string            `json:"error"`
	ID                 uuid.UUID          `json:"id"`
	WorkspaceID        uuid.UUID          `json:"workspace_id"`
}

func (q *Queries) UpdateBotJob(ctx context.Context, arg UpdateBotJobParams) (BotJob, error) {
	row := q.db.QueryRow(ctx, updateBotJob,
		arg.Status,
		arg.WorkerID,
		arg.MinutesUsed,
		arg.ConsentAnnouncedAt,
		arg.Error,
		arg.ID,
		arg.WorkspaceID,
	)
	var i BotJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.MeetingUrl,
		&i.Platform,
		&i.ScheduledAt,
		&i.Status,
		&i.WorkerID,
		&i.MinutesUsed,
		&i.ConsentAnnouncedAt,
		&i.Error,
		&i.CreatedAt,
		&i.EstimatedMinutes,
		&i.BotName,
	)
	return i, err
}
