// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (user_id, name, platform)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, platform, last_sync_at, created_at
`

type CreateDeviceParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Name     string    `json:"name"`
	Platform string    `json:"platform"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice, arg.UserID, arg.Name, arg.Platform)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Platform,
		&i.LastSyncAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :execrows
DELETE FROM devices
WHERE id = $1 AND user_id = $2
`

type DeleteDeviceParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteDevice(ctx context.Context, arg DeleteDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDevice, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDevice = `-- name: GetDevice :one
SELECT devices.id, devices.user_id, devices.name, devices.platform, devices.last_sync_at, devices.created_at FROM devices
JOIN memberships ON memberships.user_id = devices.user_id
WHERE devices.id = $1 AND memberships.workspace_id = $2
`

type GetDeviceParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetDevice(ctx context.Context, arg GetDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, arg.ID, arg.WorkspaceID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Platform,
		&i.LastSyncAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDevicesByWorkspace = `-- name: ListDevicesByWorkspace :many
SELECT DISTINCT ON (devices.created_at, devices.id) devices.id, devices.user_id, devices.name, devices.platform, devices.last_sync_at, devices.created_at
FROM devices
JOIN memberships ON memberships.user_id = devices.user_id
WHERE memberships.workspace_id = $1
  AND (
      $2::timestamptz IS NULL
      OR (devices.created_at, devices.id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY devices.created_at DESC, devices.id DESC
LIMIT $4
`

type ListDevicesByWorkspaceParams struct {
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        *uuid.UUID         `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

func (q *Queries) ListDevicesByWorkspace(ctx context.Context, arg ListDevicesByWorkspaceParams) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByWorkspace,
		arg.WorkspaceID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Platform,
			&i.LastSyncAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE devices SET
    name = COALESCE($1, name),
    last_sync_at = COALESCE($2, last_sync_at)
WHERE id = $3 AND user_id = $4
RETURNING id, user_id, name, platform, last_sync_at, created_at
`

type UpdateDeviceParams struct {
	Name       *string            `json:"name"`
	LastSyncAt pgtype.Timestamptz `json:"last_sync_at"`
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDevice,
		arg.Name,
		arg.LastSyncAt,
		arg.ID,
		arg.UserID,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Platform,
		&i.LastSyncAt,
		&i.CreatedAt,
	)
	return i, err
}
