// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: healthchecks.sql

package sqlcgen

import (
	"context"
)

const getHealthcheck = `-- name: GetHealthcheck :one
SELECT id, at FROM healthchecks WHERE id = 1
`

func (q *Queries) GetHealthcheck(ctx context.Context) (Healthcheck, error) {
	row := q.db.QueryRow(ctx, getHealthcheck)
	var i Healthcheck
	err := row.Scan(&i.ID, &i.At)
	return i, err
}

const touchHealthcheck = `-- name: TouchHealthcheck :one
UPDATE healthchecks SET at = now() WHERE id = 1 RETURNING id, at
`

func (q *Queries) TouchHealthcheck(ctx context.Context) (Healthcheck, error) {
	row := q.db.QueryRow(ctx, touchHealthcheck)
	var i Healthcheck
	err := row.Scan(&i.ID, &i.At)
	return i, err
}
