// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (kind, payload, idempotency_key, run_at, max_attempts)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (kind, idempotency_key) WHERE idempotency_key IS NOT NULL DO NOTHING
RETURNING id, kind, payload, idempotency_key, run_at, attempts, max_attempts, locked_by, locked_at, status, last_error, created_at, updated_at
`

type CreateJobParams struct {
	Kind           string             `json:"kind"`
	Payload        []byte             `json:"payload"`
	IdempotencyKey *string            `json:"idempotency_key"`
	RunAt          pgtype.Timestamptz `json:"run_at"`
	MaxAttempts    int32              `json:"max_attempts"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.Kind,
		arg.Payload,
		arg.IdempotencyKey,
		arg.RunAt,
		arg.MaxAttempts,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.IdempotencyKey,
		&i.RunAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockedAt,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :execrows
DELETE FROM jobs WHERE id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteJob, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJob = `-- name: GetJob :one
SELECT id, kind, payload, idempotency_key, run_at, attempts, max_attempts, locked_by, locked_at, status, last_error, created_at, updated_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.IdempotencyKey,
		&i.RunAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockedAt,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobByIdempotencyKey = `-- name: GetJobByIdempotencyKey :one
SELECT id, kind, payload, idempotency_key, run_at, attempts, max_attempts, locked_by, locked_at, status, last_error, created_at, updated_at FROM jobs
WHERE kind = $1 AND idempotency_key = $2
`

type GetJobByIdempotencyKeyParams struct {
	Kind           string  `json:"kind"`
	IdempotencyKey *string `json:"idempotency_key"`
}

func (q *Queries) GetJobByIdempotencyKey(ctx context.Context, arg GetJobByIdempotencyKeyParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByIdempotencyKey, arg.Kind, arg.IdempotencyKey)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.IdempotencyKey,
		&i.RunAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockedAt,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, kind, payload, idempotency_key, run_at, attempts, max_attempts, locked_by, locked_at, status, last_error, created_at, updated_at FROM jobs
WHERE ($1::text IS NULL OR status = $1::text)
  AND (
      $2::timestamptz IS NULL
      OR (created_at, id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListJobsParams struct {
	Status          *string            `json:"status"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        *uuid.UUID         `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Payload,
			&i.IdempotencyKey,
			&i.RunAt,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LockedBy,
			&i.LockedAt,
			&i.Status,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs SET
    payload = COALESCE($1, payload),
    run_at = COALESCE($2, run_at),
    max_attempts = COALESCE($3, max_attempts),
    updated_at = now()
WHERE id = $4 AND status <> 'running'
RETURNING id, kind, payload, idempotency_key, run_at, attempts, max_attempts, locked_by, locked_at, status, last_error, created_at, updated_at
`

type UpdateJobParams struct {
	Payload     []byte             `json:"payload"`
	RunAt       pgtype.Timestamptz `json:"run_at"`
	MaxAttempts *int32             `json:"max_attempts"`
	ID          uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJob,
		arg.Payload,
		arg.RunAt,
		arg.MaxAttempts,
		arg.ID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.IdempotencyKey,
		&i.RunAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockedAt,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
