// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: library.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countChildFolders = `-- name: CountChildFolders :one
SELECT COUNT(*) FROM folders
WHERE workspace_id = $1 AND parent_id = $2
`

type CountChildFoldersParams struct {
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	ParentID    *uuid.UUID `json:"parent_id"`
}

func (q *Queries) CountChildFolders(ctx context.Context, arg CountChildFoldersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countChildFolders, arg.WorkspaceID, arg.ParentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSegmentsForMeeting = `-- name: CountSegmentsForMeeting :one
SELECT COUNT(*) FROM transcript_segments
JOIN meetings ON meetings.id = transcript_segments.meeting_id
WHERE transcript_segments.meeting_id = $1
  AND meetings.workspace_id = $2
`

type CountSegmentsForMeetingParams struct {
	MeetingID   uuid.UUID `json:"meeting_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) CountSegmentsForMeeting(ctx context.Context, arg CountSegmentsForMeetingParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSegmentsForMeeting, arg.MeetingID, arg.WorkspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredShareLinkRequests = `-- name: DeleteExpiredShareLinkRequests :execrows
DELETE FROM share_link_requests WHERE created_at < $1
`

func (q *Queries) DeleteExpiredShareLinkRequests(ctx context.Context, before pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredShareLinkRequests, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMeetingReturning = `-- name: DeleteMeetingReturning :one
DELETE FROM meetings
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, owner_user_id, title, source, platform, started_at, duration_s, consent_state, visibility, folder_id, audio_object, transcript_object, status, created_at, audio_bytes, transcript_bytes, link_sharing_enabled, finalize_generation
`

type DeleteMeetingReturningParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteMeetingReturning(ctx context.Context, arg DeleteMeetingReturningParams) (Meeting, error) {
	row := q.db.QueryRow(ctx, deleteMeetingReturning, arg.ID, arg.WorkspaceID)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.OwnerUserID,
		&i.Title,
		&i.Source,
		&i.Platform,
		&i.StartedAt,
		&i.DurationS,
		&i.ConsentState,
		&i.Visibility,
		&i.FolderID,
		&i.AudioObject,
		&i.TranscriptObject,
		&i.Status,
		&i.CreatedAt,
		&i.AudioBytes,
		&i.TranscriptBytes,
		&i.LinkSharingEnabled,
		&i.FinalizeGeneration,
	)
	return i, err
}

const deleteSegmentsForMeeting = `-- name: DeleteSegmentsForMeeting :execrows
DELETE FROM transcript_segments
USING meetings
WHERE transcript_segments.meeting_id = meetings.id
  AND meetings.id = $1
  AND meetings.workspace_id = $2
`

type DeleteSegmentsForMeetingParams struct {
	MeetingID   uuid.UUID `json:"meeting_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteSegmentsForMeeting(ctx context.Context, arg DeleteSegmentsForMeetingParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSegmentsForMeeting, arg.MeetingID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteShareLinksForMeeting = `-- name: DeleteShareLinksForMeeting :execrows
DELETE FROM share_links
USING meetings
WHERE share_links.meeting_id = meetings.id
  AND meetings.id = $1
  AND meetings.workspace_id = $2
`

type DeleteShareLinksForMeetingParams struct {
	MeetingID   uuid.UUID `json:"meeting_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteShareLinksForMeeting(ctx context.Context, arg DeleteShareLinksForMeetingParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteShareLinksForMeeting, arg.MeetingID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finalizeMeetingObjects = `-- name: FinalizeMeetingObjects :one
UPDATE meetings SET
    status = $1,
    audio_bytes = $2,
    transcript_bytes = $3,
    duration_s = COALESCE($4, duration_s),
    finalize_generation = $5
WHERE id = $6 AND workspace_id = $7
RETURNING id, workspace_id, owner_user_id, title, source, platform, started_at, duration_s, consent_state, visibility, folder_id, audio_object, transcript_object, status, created_at, audio_bytes, transcript_bytes, link_sharing_enabled, finalize_generation
`

type FinalizeMeetingObjectsParams struct {
	Status             string    `json:"status"`
	AudioBytes         *int64    `json:"audio_bytes"`
	TranscriptBytes    *int64    `json:"transcript_bytes"`
	DurationS          *int32    `json:"duration_s"`
	FinalizeGeneration int32     `json:"finalize_generation"`
	ID                 uuid.UUID `json:"id"`
	WorkspaceID        uuid.UUID `json:"workspace_id"`
}

func (q *Queries) FinalizeMeetingObjects(ctx context.Context, arg FinalizeMeetingObjectsParams) (Meeting, error) {
	row := q.db.QueryRow(ctx, finalizeMeetingObjects,
		arg.Status,
		arg.AudioBytes,
		arg.TranscriptBytes,
		arg.DurationS,
		arg.FinalizeGeneration,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.OwnerUserID,
		&i.Title,
		&i.Source,
		&i.Platform,
		&i.StartedAt,
		&i.DurationS,
		&i.ConsentState,
		&i.Visibility,
		&i.FolderID,
		&i.AudioObject,
		&i.TranscriptObject,
		&i.Status,
		&i.CreatedAt,
		&i.AudioBytes,
		&i.TranscriptBytes,
		&i.LinkSharingEnabled,
		&i.FinalizeGeneration,
	)
	return i, err
}

const getMeetingByShareTokenHash = `-- name: GetMeetingByShareTokenHash :one
SELECT meetings.id, meetings.workspace_id, meetings.owner_user_id, meetings.title, meetings.source, meetings.platform, meetings.started_at, meetings.duration_s, meetings.consent_state, meetings.visibility, meetings.folder_id, meetings.audio_object, meetings.transcript_object, meetings.status, meetings.created_at, meetings.audio_bytes, meetings.transcript_bytes, meetings.link_sharing_enabled, meetings.finalize_generation, share_links.id, share_links.meeting_id, share_links.permission, share_links.expires_at, share_links.created_at, share_links.token_hash
FROM share_links
JOIN meetings ON meetings.id = share_links.meeting_id
WHERE share_links.token_hash = $1
`

type GetMeetingByShareTokenHashRow struct {
	Meeting   Meeting   `json:"meeting"`
	ShareLink ShareLink `json:"share_link"`
}

func (q *Queries) GetMeetingByShareTokenHash(ctx context.Context, tokenHash string) (GetMeetingByShareTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getMeetingByShareTokenHash, tokenHash)
	var i GetMeetingByShareTokenHashRow
	err := row.Scan(
		&i.Meeting.ID,
		&i.Meeting.WorkspaceID,
		&i.Meeting.OwnerUserID,
		&i.Meeting.Title,
		&i.Meeting.Source,
		&i.Meeting.Platform,
		&i.Meeting.StartedAt,
		&i.Meeting.DurationS,
		&i.Meeting.ConsentState,
		&i.Meeting.Visibility,
		&i.Meeting.FolderID,
		&i.Meeting.AudioObject,
		&i.Meeting.TranscriptObject,
		&i.Meeting.Status,
		&i.Meeting.CreatedAt,
		&i.Meeting.AudioBytes,
		&i.Meeting.TranscriptBytes,
		&i.Meeting.LinkSharingEnabled,
		&i.Meeting.FinalizeGeneration,
		&i.ShareLink.ID,
		&i.ShareLink.MeetingID,
		&i.ShareLink.Permission,
		&i.ShareLink.ExpiresAt,
		&i.ShareLink.CreatedAt,
		&i.ShareLink.TokenHash,
	)
	return i, err
}

const listClipObjectsForMeeting = `-- name: ListClipObjectsForMeeting :many
SELECT clips.object FROM clips
JOIN meetings ON meetings.id = clips.meeting_id
WHERE clips.meeting_id = $1
  AND meetings.workspace_id = $2
  AND clips.object IS NOT NULL
`

type ListClipObjectsForMeetingParams struct {
	MeetingID   uuid.UUID `json:"meeting_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) ListClipObjectsForMeeting(ctx context.Context, arg ListClipObjectsForMeetingParams) ([]*string, error) {
	rows, err := q.db.Query(ctx, listClipObjectsForMeeting, arg.MeetingID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var object *string
		if err := rows.Scan(&object); err != nil {
			return nil, err
		}
		items = append(items, object)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFolders = `-- name: ListFolders :many
SELECT id, workspace_id, name, parent_id, created_at FROM folders
WHERE workspace_id = $1
ORDER BY name, id
`

func (q *Queries) ListFolders(ctx context.Context, workspaceID uuid.UUID) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFolders, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeetingsPage = `-- name: ListMeetingsPage :many
SELECT id, workspace_id, owner_user_id, title, source, platform, started_at, duration_s, consent_state, visibility, folder_id, audio_object, transcript_object, status, created_at, audio_bytes, transcript_bytes, link_sharing_enabled, finalize_generation FROM meetings
WHERE workspace_id = $1
  AND (visibility <> 'private' OR owner_user_id = $2)
  AND ($3::uuid IS NULL OR folder_id = $3::uuid)
  AND ($4::text IS NULL OR source = $4::text)
  AND ($5::timestamptz IS NULL OR COALESCE(started_at, created_at) >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR COALESCE(started_at, created_at) <= $6::timestamptz)
  AND ($7::text IS NULL OR title ILIKE '%' || $7::text || '%' ESCAPE '\')
  AND (
      $8::timestamptz IS NULL
      OR (created_at, id) < ($8::timestamptz, $9::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $10
`

type ListMeetingsPageParams struct {
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	ViewerUserID    *uuid.UUID         `json:"viewer_user_id"`
	FolderID        *uuid.UUID         `json:"folder_id"`
	Source          *string            `json:"source"`
	FromTime        pgtype.Timestamptz `json:"from_time"`
	ToTime          pgtype.Timestamptz `json:"to_time"`
	Search          *string            `json:"search"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        *uuid.UUID         `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

func (q *Queries) ListMeetingsPage(ctx context.Context, arg ListMeetingsPageParams) ([]Meeting, error) {
	rows, err := q.db.Query(ctx, listMeetingsPage,
		arg.WorkspaceID,
		arg.ViewerUserID,
		arg.FolderID,
		arg.Source,
		arg.FromTime,
		arg.ToTime,
		arg.Search,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Meeting{}
	for rows.Next() {
		var i Meeting
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.OwnerUserID,
			&i.Title,
			&i.Source,
			&i.Platform,
			&i.StartedAt,
			&i.DurationS,
			&i.ConsentState,
			&i.Visibility,
			&i.FolderID,
			&i.AudioObject,
			&i.TranscriptObject,
			&i.Status,
			&i.CreatedAt,
			&i.AudioBytes,
			&i.TranscriptBytes,
			&i.LinkSharingEnabled,
			&i.FinalizeGeneration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSegmentsBySeq = `-- name: ListSegmentsBySeq :many
SELECT transcript_segments.id, transcript_segments.meeting_id, transcript_segments.seq,
       transcript_segments.speaker, transcript_segments.start_s, transcript_segments.end_s,
       transcript_segments.text, transcript_segments.created_at
FROM transcript_segments
JOIN meetings ON meetings.id = transcript_segments.meeting_id
WHERE transcript_segments.meeting_id = $1
  AND meetings.workspace_id = $2
  AND ($3::integer IS NULL OR transcript_segments.seq > $3::integer)
ORDER BY transcript_segments.seq
LIMIT $4
`

type ListSegmentsBySeqParams struct {
	MeetingID   uuid.UUID `json:"meeting_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	AfterSeq    *int32    `json:"after_seq"`
	PageSize    int32     `json:"page_size"`
}

type ListSegmentsBySeqRow struct {
	ID        uuid.UUID          `json:"id"`
	MeetingID uuid.UUID          `json:"meeting_id"`
	Seq       int32              `json:"seq"`
	Speaker   *string            `json:"speaker"`
	StartS    float64            `json:"start_s"`
	EndS      float64            `json:"end_s"`
	Text      string             `json:"text"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListSegmentsBySeq(ctx context.Context, arg ListSegmentsBySeqParams) ([]ListSegmentsBySeqRow, error) {
	rows, err := q.db.Query(ctx, listSegmentsBySeq,
		arg.MeetingID,
		arg.WorkspaceID,
		arg.AfterSeq,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSegmentsBySeqRow{}
	for rows.Next() {
		var i ListSegmentsBySeqRow
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.Seq,
			&i.Speaker,
			&i.StartS,
			&i.EndS,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShareLinksForMeeting = `-- name: ListShareLinksForMeeting :many
SELECT share_links.id, share_links.meeting_id, share_links.permission, share_links.expires_at, share_links.created_at, share_links.token_hash FROM share_links
JOIN meetings ON meetings.id = share_links.meeting_id
WHERE share_links.meeting_id = $1
  AND meetings.workspace_id = $2
ORDER BY share_links.created_at DESC, share_links.id DESC
`

type ListShareLinksForMeetingParams struct {
	MeetingID   uuid.UUID `json:"meeting_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) ListShareLinksForMeeting(ctx context.Context, arg ListShareLinksForMeetingParams) ([]ShareLink, error) {
	rows, err := q.db.Query(ctx, listShareLinksForMeeting, arg.MeetingID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShareLink{}
	for rows.Next() {
		var i ShareLink
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.Permission,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.TokenHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockShareLinkIP = `-- name: LockShareLinkIP :exec
SELECT pg_advisory_xact_lock(hashtext($1::text))
`

func (q *Queries) LockShareLinkIP(ctx context.Context, requestIp string) error {
	_, err := q.db.Exec(ctx, lockShareLinkIP, requestIp)
	return err
}

const setMeetingLinkSharing = `-- name: SetMeetingLinkSharing :one
UPDATE meetings SET link_sharing_enabled = $1
WHERE id = $2 AND workspace_id = $3
RETURNING id, workspace_id, owner_user_id, title, source, platform, started_at, duration_s, consent_state, visibility, folder_id, audio_object, transcript_object, status, created_at, audio_bytes, transcript_bytes, link_sharing_enabled, finalize_generation
`

type SetMeetingLinkSharingParams struct {
	LinkSharingEnabled bool      `json:"link_sharing_enabled"`
	ID                 uuid.UUID `json:"id"`
	WorkspaceID        uuid.UUID `json:"workspace_id"`
}

func (q *Queries) SetMeetingLinkSharing(ctx context.Context, arg SetMeetingLinkSharingParams) (Meeting, error) {
	row := q.db.QueryRow(ctx, setMeetingLinkSharing, arg.LinkSharingEnabled, arg.ID, arg.WorkspaceID)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.OwnerUserID,
		&i.Title,
		&i.Source,
		&i.Platform,
		&i.StartedAt,
		&i.DurationS,
		&i.ConsentState,
		&i.Visibility,
		&i.FolderID,
		&i.AudioObject,
		&i.TranscriptObject,
		&i.Status,
		&i.CreatedAt,
		&i.AudioBytes,
		&i.TranscriptBytes,
		&i.LinkSharingEnabled,
		&i.FinalizeGeneration,
	)
	return i, err
}

const tryRecordShareLinkRequest = `-- name: TryRecordShareLinkRequest :one
INSERT INTO share_link_requests (request_ip, created_at)
SELECT $1, $2
WHERE (
    SELECT count(*) FROM share_link_requests AS recent
    WHERE recent.request_ip = $1 AND recent.created_at >= $3
) < $4::bigint
RETURNING id
`

type TryRecordShareLinkRequestParams struct {
	RequestIp    string             `json:"request_ip"`
	RecordedAt   pgtype.Timestamptz `json:"recorded_at"`
	Since        pgtype.Timestamptz `json:"since"`
	RequestLimit int64              `json:"request_limit"`
}

func (q *Queries) TryRecordShareLinkRequest(ctx context.Context, arg TryRecordShareLinkRequestParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, tryRecordShareLinkRequest,
		arg.RequestIp,
		arg.RecordedAt,
		arg.Since,
		arg.RequestLimit,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateFolderDetails = `-- name: UpdateFolderDetails :one
UPDATE folders SET
    name = COALESCE($1, name),
    parent_id = CASE
        WHEN $2::boolean THEN NULL
        ELSE COALESCE($3, parent_id)
    END
WHERE id = $4 AND workspace_id = $5
RETURNING id, workspace_id, name, parent_id, created_at
`

type UpdateFolderDetailsParams struct {
	Name        *string    `json:"name"`
	ClearParent bool       `json:"clear_parent"`
	ParentID    *uuid.UUID `json:"parent_id"`
	ID          uuid.UUID  `json:"id"`
	WorkspaceID uuid.UUID  `json:"workspace_id"`
}

func (q *Queries) UpdateFolderDetails(ctx context.Context, arg UpdateFolderDetailsParams) (Folder, error) {
	row := q.db.QueryRow(ctx, updateFolderDetails,
		arg.Name,
		arg.ClearParent,
		arg.ParentID,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
	)
	return i, err
}

const updateMeetingDetails = `-- name: UpdateMeetingDetails :one
UPDATE meetings SET
    title = COALESCE($1, title),
    visibility = COALESCE($2, visibility),
    folder_id = CASE
        WHEN $3::boolean THEN NULL
        ELSE COALESCE($4, folder_id)
    END
WHERE id = $5 AND workspace_id = $6
RETURNING id, workspace_id, owner_user_id, title, source, platform, started_at, duration_s, consent_state, visibility, folder_id, audio_object, transcript_object, status, created_at, audio_bytes, transcript_bytes, link_sharing_enabled, finalize_generation
`

type UpdateMeetingDetailsParams struct {
	Title       *string    `json:"title"`
	Visibility  *string    `json:"visibility"`
	ClearFolder bool       `json:"clear_folder"`
	FolderID    *uuid.UUID `json:"folder_id"`
	ID          uuid.UUID  `json:"id"`
	WorkspaceID uuid.UUID  `json:"workspace_id"`
}

func (q *Queries) UpdateMeetingDetails(ctx context.Context, arg UpdateMeetingDetailsParams) (Meeting, error) {
	row := q.db.QueryRow(ctx, updateMeetingDetails,
		arg.Title,
		arg.Visibility,
		arg.ClearFolder,
		arg.FolderID,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.OwnerUserID,
		&i.Title,
		&i.Source,
		&i.Platform,
		&i.StartedAt,
		&i.DurationS,
		&i.ConsentState,
		&i.Visibility,
		&i.FolderID,
		&i.AudioObject,
		&i.TranscriptObject,
		&i.Status,
		&i.CreatedAt,
		&i.AudioBytes,
		&i.TranscriptBytes,
		&i.LinkSharingEnabled,
		&i.FinalizeGeneration,
	)
	return i, err
}
