// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meetings.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMeeting = `-- name: CreateMeeting :one
INSERT INTO meetings (
    workspace_id, owner_user_id, title, source, platform, started_at, duration_s,
    consent_state, visibility, folder_id, audio_object, transcript_object, status
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11,
    $12, $13
)
RETURNING id, workspace_id, owner_user_id, title, source, platform, started_at, duration_s, consent_state, visibility, folder_id, audio_object, transcript_object, status, created_at, audio_bytes, transcript_bytes, link_sharing_enabled, finalize_generation
`

type CreateMeetingParams struct {
	WorkspaceID      uuid.UUID          `json:"workspace_id"`
	OwnerUserID      *uuid.UUID         `json:"owner_user_id"`
	Title            string             `json:"title"`
	Source           string             `json:"source"`
	Platform         *string            `json:"platform"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	DurationS        int32              `json:"duration_s"`
	ConsentState     string             `json:"consent_state"`
	Visibility       string             `json:"visibility"`
	FolderID         *uuid.UUID         `json:"folder_id"`
	AudioObject      *string            `json:"audio_object"`
	TranscriptObject *string            `json:"transcript_object"`
	Status           string             `json:"status"`
}

func (q *Queries) CreateMeeting(ctx context.Context, arg CreateMeetingParams) (Meeting, error) {
	row := q.db.QueryRow(ctx, createMeeting,
		arg.WorkspaceID,
		arg.OwnerUserID,
		arg.Title,
		arg.Source,
		arg.Platform,
		arg.StartedAt,
		arg.DurationS,
		arg.ConsentState,
		arg.Visibility,
		arg.FolderID,
		arg.AudioObject,
		arg.TranscriptObject,
		arg.Status,
	)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.OwnerUserID,
		&i.Title,
		&i.Source,
		&i.Platform,
		&i.StartedAt,
		&i.DurationS,
		&i.ConsentState,
		&i.Visibility,
		&i.FolderID,
		&i.AudioObject,
		&i.TranscriptObject,
		&i.Status,
		&i.CreatedAt,
		&i.AudioBytes,
		&i.TranscriptBytes,
		&i.LinkSharingEnabled,
		&i.FinalizeGeneration,
	)
	return i, err
}

const deleteMeeting = `-- name: DeleteMeeting :execrows
DELETE FROM meetings
WHERE id = $1 AND workspace_id = $2
`

type DeleteMeetingParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteMeeting(ctx context.Context, arg DeleteMeetingParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMeeting, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMeeting = `-- name: GetMeeting :one
SELECT id, workspace_id, owner_user_id, title, source, platform, started_at, duration_s, consent_state, visibility, folder_id, audio_object, transcript_object, status, created_at, audio_bytes, transcript_bytes, link_sharing_enabled, finalize_generation FROM meetings
WHERE id = $1 AND workspace_id = $2
`

type GetMeetingParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetMeeting(ctx context.Context, arg GetMeetingParams) (Meeting, error) {
	row := q.db.QueryRow(ctx, getMeeting, arg.ID, arg.WorkspaceID)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.OwnerUserID,
		&i.Title,
		&i.Source,
		&i.Platform,
		&i.StartedAt,
		&i.DurationS,
		&i.ConsentState,
		&i.Visibility,
		&i.FolderID,
		&i.AudioObject,
		&i.TranscriptObject,
		&i.Status,
		&i.CreatedAt,
		&i.AudioBytes,
		&i.TranscriptBytes,
		&i.LinkSharingEnabled,
		&i.FinalizeGeneration,
	)
	return i, err
}

const listMeetingsByWorkspace = `-- name: ListMeetingsByWorkspace :many
SELECT id, workspace_id, owner_user_id, title, source, platform, started_at, duration_s, consent_state, visibility, folder_id, audio_object, transcript_object, status, created_at, audio_bytes, transcript_bytes, link_sharing_enabled, finalize_generation FROM meetings
WHERE workspace_id = $1
  AND (
      $2::timestamptz IS NULL
      OR (created_at, id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListMeetingsByWorkspaceParams struct {
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        *uuid.UUID         `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

func (q *Queries) ListMeetingsByWorkspace(ctx context.Context, arg ListMeetingsByWorkspaceParams) ([]Meeting, error) {
	rows, err := q.db.Query(ctx, listMeetingsByWorkspace,
		arg.WorkspaceID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Meeting{}
	for rows.Next() {
		var i Meeting
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.OwnerUserID,
			&i.Title,
			&i.Source,
			&i.Platform,
			&i.StartedAt,
			&i.DurationS,
			&i.ConsentState,
			&i.Visibility,
			&i.FolderID,
			&i.AudioObject,
			&i.TranscriptObject,
			&i.Status,
			&i.CreatedAt,
			&i.AudioBytes,
			&i.TranscriptBytes,
			&i.LinkSharingEnabled,
			&i.FinalizeGeneration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMeeting = `-- name: UpdateMeeting :one
UPDATE meetings SET
    title = COALESCE($1, title),
    platform = COALESCE($2, platform),
    started_at = COALESCE($3, started_at),
    duration_s = COALESCE($4, duration_s),
    consent_state = COALESCE($5, consent_state),
    visibility = COALESCE($6, visibility),
    folder_id = COALESCE($7, folder_id),
    audio_object = COALESCE($8, audio_object),
    transcript_object = COALESCE($9, transcript_object),
    status = COALESCE($10, status)
WHERE id = $11 AND workspace_id = $12
RETURNING id, workspace_id, owner_user_id, title, source, platform, started_at, duration_s, consent_state, visibility, folder_id, audio_object, transcript_object, status, created_at, audio_bytes, transcript_bytes, link_sharing_enabled, finalize_generation
`

type UpdateMeetingParams struct {
	Title            *string            `json:"title"`
	Platform         *string            `json:"platform"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	DurationS        *int32             `json:"duration_s"`
	ConsentState     *string            `json:"consent_state"`
	Visibility       *string            `json:"visibility"`
	FolderID         *uuid.UUID         `json:"folder_id"`
	AudioObject      *string            `json:"audio_object"`
	TranscriptObject *string            `json:"transcript_object"`
	Status           *string            `json:"status"`
	ID               uuid.UUID          `json:"id"`
	WorkspaceID      uuid.UUID          `json:"workspace_id"`
}

func (q *Queries) UpdateMeeting(ctx context.Context, arg UpdateMeetingParams) (Meeting, error) {
	row := q.db.QueryRow(ctx, updateMeeting,
		arg.Title,
		arg.Platform,
		arg.StartedAt,
		arg.DurationS,
		arg.ConsentState,
		arg.Visibility,
		arg.FolderID,
		arg.AudioObject,
		arg.TranscriptObject,
		arg.Status,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.OwnerUserID,
		&i.Title,
		&i.Source,
		&i.Platform,
		&i.StartedAt,
		&i.DurationS,
		&i.ConsentState,
		&i.Visibility,
		&i.FolderID,
		&i.AudioObject,
		&i.TranscriptObject,
		&i.Status,
		&i.CreatedAt,
		&i.AudioBytes,
		&i.TranscriptBytes,
		&i.LinkSharingEnabled,
		&i.FinalizeGeneration,
	)
	return i, err
}
