// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (workspace_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING workspace_id, user_id, role, created_at
`

type CreateMembershipParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.WorkspaceID, arg.UserID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :execrows
DELETE FROM memberships
WHERE workspace_id = $1 AND user_id = $2
`

type DeleteMembershipParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMembership, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMembership = `-- name: GetMembership :one
SELECT workspace_id, user_id, role, created_at FROM memberships
WHERE workspace_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.WorkspaceID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listMembershipsByWorkspace = `-- name: ListMembershipsByWorkspace :many
SELECT workspace_id, user_id, role, created_at FROM memberships
WHERE workspace_id = $1
  AND (
      $2::timestamptz IS NULL
      OR (created_at, user_id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY created_at DESC, user_id DESC
LIMIT $4
`

type ListMembershipsByWorkspaceParams struct {
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        *uuid.UUID         `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

func (q *Queries) ListMembershipsByWorkspace(ctx context.Context, arg ListMembershipsByWorkspaceParams) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listMembershipsByWorkspace,
		arg.WorkspaceID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Membership{}
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMembership = `-- name: UpdateMembership :one
UPDATE memberships SET role = $1
WHERE workspace_id = $2 AND user_id = $3
RETURNING workspace_id, user_id, role, created_at
`

type UpdateMembershipParams struct {
	Role        string    `json:"role"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateMembership(ctx context.Context, arg UpdateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, updateMembership, arg.Role, arg.WorkspaceID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
