// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type ApiToken struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Hash        string             `json:"hash"`
	Scopes      []string           `json:"scopes"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	ActorUserID *uuid.UUID         `json:"actor_user_id"`
	Action      string             `json:"action"`
	Target      string             `json:"target"`
	At          pgtype.Timestamptz `json:"at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AuthOtp struct {
	ID          uuid.UUID          `json:"id"`
	Channel     string             `json:"channel"`
	Destination string             `json:"destination"`
	CodeHash    string             `json:"code_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	Attempts    int32              `json:"attempts"`
	ConsumedAt  pgtype.Timestamptz `json:"consumed_at"`
	RequestIp   string             `json:"request_ip"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type BotJob struct {
	ID                 uuid.UUID          `json:"id"`
	WorkspaceID        uuid.UUID          `json:"workspace_id"`
	MeetingUrl         string             `json:"meeting_url"`
	Platform           string             `json:"platform"`
	ScheduledAt        pgtype.Timestamptz `json:"scheduled_at"`
	Status             string             `json:"status"`
	WorkerID           *string            `json:"worker_id"`
	MinutesUsed        int32              `json:"minutes_used"`
	ConsentAnnouncedAt pgtype.Timestamptz `json:"consent_announced_at"`
	Error              *string            `json:"error"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type CalendarConnection struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Provider        string             `json:"provider"`
	RefreshTokenEnc []byte             `json:"refresh_token_enc"`
	AutoJoinRule    []byte             `json:"auto_join_rule"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Clip struct {
	ID         uuid.UUID          `json:"id"`
	MeetingID  uuid.UUID          `json:"meeting_id"`
	StartS     float64            `json:"start_s"`
	EndS       float64            `json:"end_s"`
	Title      string             `json:"title"`
	Object     *string            `json:"object"`
	ShareToken *string            `json:"share_token"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Comment struct {
	ID        uuid.UUID          `json:"id"`
	MeetingID uuid.UUID          `json:"meeting_id"`
	UserID    *uuid.UUID         `json:"user_id"`
	AtS       float64            `json:"at_s"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CreditLedger struct {
	ID           uuid.UUID          `json:"id"`
	WorkspaceID  uuid.UUID          `json:"workspace_id"`
	DeltaMinutes int32              `json:"delta_minutes"`
	Reason       string             `json:"reason"`
	RefID        *string            `json:"ref_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type CreditLock struct {
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type CreditPack struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	Minutes    int32              `json:"minutes"`
	PriceMinor int64              `json:"price_minor"`
	Currency   string             `json:"currency"`
	Active     bool               `json:"active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Device struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	Platform   string             `json:"platform"`
	LastSyncAt pgtype.Timestamptz `json:"last_sync_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Folder struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Name        string             `json:"name"`
	ParentID    *uuid.UUID         `json:"parent_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Healthcheck struct {
	ID int32              `json:"id"`
	At pgtype.Timestamptz `json:"at"`
}

type Job struct {
	ID             uuid.UUID          `json:"id"`
	Kind           string             `json:"kind"`
	Payload        []byte             `json:"payload"`
	IdempotencyKey *string            `json:"idempotency_key"`
	RunAt          pgtype.Timestamptz `json:"run_at"`
	Attempts       int32              `json:"attempts"`
	MaxAttempts    int32              `json:"max_attempts"`
	LockedBy       *string            `json:"locked_by"`
	LockedAt       pgtype.Timestamptz `json:"locked_at"`
	Status         string             `json:"status"`
	LastError      *string            `json:"last_error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type KeywordAlert struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Phrase      string             `json:"phrase"`
	Channel     string             `json:"channel"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Meeting struct {
	ID                 uuid.UUID          `json:"id"`
	WorkspaceID        uuid.UUID          `json:"workspace_id"`
	OwnerUserID        *uuid.UUID         `json:"owner_user_id"`
	Title              string             `json:"title"`
	Source             string             `json:"source"`
	Platform           *string            `json:"platform"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	DurationS          int32              `json:"duration_s"`
	ConsentState       string             `json:"consent_state"`
	Visibility         string             `json:"visibility"`
	FolderID           *uuid.UUID         `json:"folder_id"`
	AudioObject        *string            `json:"audio_object"`
	TranscriptObject   *string            `json:"transcript_object"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	AudioBytes         *int64             `json:"audio_bytes"`
	TranscriptBytes    *int64             `json:"transcript_bytes"`
	LinkSharingEnabled bool               `json:"link_sharing_enabled"`
	FinalizeGeneration int32              `json:"finalize_generation"`
}

type Membership struct {
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type OauthState struct {
	ID           uuid.UUID          `json:"id"`
	Provider     string             `json:"provider"`
	StateHash    string             `json:"state_hash"`
	CodeVerifier string             `json:"code_verifier"`
	RedirectTo   string             `json:"redirect_to"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	NonceHash    string             `json:"nonce_hash"`
}

type Payment struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Provider    string             `json:"provider"`
	ProviderRef string             `json:"provider_ref"`
	AmountMinor int64              `json:"amount_minor"`
	Currency    string             `json:"currency"`
	Minutes     int32              `json:"minutes"`
	Status      string             `json:"status"`
	Raw         []byte             `json:"raw"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	FamilyID   uuid.UUID          `json:"family_id"`
	TokenHash  string             `json:"token_hash"`
	DeviceID   string             `json:"device_id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ShareLink struct {
	ID         uuid.UUID          `json:"id"`
	MeetingID  uuid.UUID          `json:"meeting_id"`
	Permission string             `json:"permission"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	TokenHash  string             `json:"token_hash"`
}

type ShareLinkRequest struct {
	ID        uuid.UUID          `json:"id"`
	RequestIp string             `json:"request_ip"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Summary struct {
	ID          uuid.UUID          `json:"id"`
	MeetingID   uuid.UUID          `json:"meeting_id"`
	TemplateID  *string            `json:"template_id"`
	Language    string             `json:"language"`
	Markdown    string             `json:"markdown"`
	Model       string             `json:"model"`
	ActionItems []byte             `json:"action_items"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type TranscriptSegment struct {
	ID        uuid.UUID          `json:"id"`
	MeetingID uuid.UUID          `json:"meeting_id"`
	Seq       int32              `json:"seq"`
	Speaker   *string            `json:"speaker"`
	StartS    float64            `json:"start_s"`
	EndS      float64            `json:"end_s"`
	Text      string             `json:"text"`
	Tsv       interface{}        `json:"tsv"`
	Embedding *pgvector.Vector   `json:"embedding"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	Email     *string            `json:"email"`
	Phone     *string            `json:"phone"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Workspace struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	Slug          string             `json:"slug"`
	BotName       string             `json:"bot_name"`
	RetentionDays int32              `json:"retention_days"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type WorkspaceInvite struct {
	ID               uuid.UUID          `json:"id"`
	WorkspaceID      uuid.UUID          `json:"workspace_id"`
	Email            string             `json:"email"`
	Role             string             `json:"role"`
	TokenHash        string             `json:"token_hash"`
	InvitedByUserID  *uuid.UUID         `json:"invited_by_user_id"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt       pgtype.Timestamptz `json:"accepted_at"`
	AcceptedByUserID *uuid.UUID         `json:"accepted_by_user_id"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}
