// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (workspace_id, provider, provider_ref, amount_minor, currency, minutes, status, raw)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8)
RETURNING id, workspace_id, provider, provider_ref, amount_minor, currency, minutes, status, raw, created_at
`

type CreatePaymentParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Provider    string    `json:"provider"`
	ProviderRef string    `json:"provider_ref"`
	AmountMinor int64     `json:"amount_minor"`
	Currency    string    `json:"currency"`
	Minutes     int32     `json:"minutes"`
	Status      string    `json:"status"`
	Raw         []byte    `json:"raw"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.WorkspaceID,
		arg.Provider,
		arg.ProviderRef,
		arg.AmountMinor,
		arg.Currency,
		arg.Minutes,
		arg.Status,
		arg.Raw,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.ProviderRef,
		&i.AmountMinor,
		&i.Currency,
		&i.Minutes,
		&i.Status,
		&i.Raw,
		&i.CreatedAt,
	)
	return i, err
}

const deletePayment = `-- name: DeletePayment :execrows
DELETE FROM payments
WHERE id = $1 AND workspace_id = $2
`

type DeletePaymentParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeletePayment(ctx context.Context, arg DeletePaymentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePayment, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPayment = `-- name: GetPayment :one
SELECT id, workspace_id, provider, provider_ref, amount_minor, currency, minutes, status, raw, created_at FROM payments
WHERE id = $1 AND workspace_id = $2
`

type GetPaymentParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetPayment(ctx context.Context, arg GetPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, arg.ID, arg.WorkspaceID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.ProviderRef,
		&i.AmountMinor,
		&i.Currency,
		&i.Minutes,
		&i.Status,
		&i.Raw,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByProviderRef = `-- name: GetPaymentByProviderRef :one
SELECT id, workspace_id, provider, provider_ref, amount_minor, currency, minutes, status, raw, created_at FROM payments
WHERE provider = $1 AND provider_ref = $2
`

type GetPaymentByProviderRefParams struct {
	Provider    string `json:"provider"`
	ProviderRef string `json:"provider_ref"`
}

func (q *Queries) GetPaymentByProviderRef(ctx context.Context, arg GetPaymentByProviderRefParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByProviderRef, arg.Provider, arg.ProviderRef)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.ProviderRef,
		&i.AmountMinor,
		&i.Currency,
		&i.Minutes,
		&i.Status,
		&i.Raw,
		&i.CreatedAt,
	)
	return i, err
}

const listPaymentsByWorkspace = `-- name: ListPaymentsByWorkspace :many
SELECT id, workspace_id, provider, provider_ref, amount_minor, currency, minutes, status, raw, created_at FROM payments
WHERE workspace_id = $1
  AND (
      $2::timestamptz IS NULL
      OR (created_at, id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListPaymentsByWorkspaceParams struct {
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        *uuid.UUID         `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

func (q *Queries) ListPaymentsByWorkspace(ctx context.Context, arg ListPaymentsByWorkspaceParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByWorkspace,
		arg.WorkspaceID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Provider,
			&i.ProviderRef,
			&i.AmountMinor,
			&i.Currency,
			&i.Minutes,
			&i.Status,
			&i.Raw,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePayment = `-- name: UpdatePayment :one
UPDATE payments SET
    status = COALESCE($1, status),
    minutes = COALESCE($2, minutes),
    raw = COALESCE($3, raw)
WHERE id = $4 AND workspace_id = $5
RETURNING id, workspace_id, provider, provider_ref, amount_minor, currency, minutes, status, raw, created_at
`

type UpdatePaymentParams struct {
	Status      *string   `json:"status"`
	Minutes     *int32    `json:"minutes"`
	Raw         []byte    `json:"raw"`
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePayment,
		arg.Status,
		arg.Minutes,
		arg.Raw,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.ProviderRef,
		&i.AmountMinor,
		&i.Currency,
		&i.Minutes,
		&i.Status,
		&i.Raw,
		&i.CreatedAt,
	)
	return i, err
}
