// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, family_id, token_hash, device_id, expires_at, created_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, user_id, family_id, token_hash, device_id, expires_at, revoked_at, last_used_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	FamilyID  uuid.UUID          `json:"family_id"`
	TokenHash string             `json:"token_hash"`
	DeviceID  string             `json:"device_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.DeviceID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.DeviceID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execrows
DELETE FROM refresh_tokens WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context, before pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRefreshTokens, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, family_id, token_hash, device_id, expires_at, revoked_at, last_used_at, created_at FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.DeviceID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listRefreshTokensByUser = `-- name: ListRefreshTokensByUser :many
SELECT id, user_id, family_id, token_hash, device_id, expires_at, revoked_at, last_used_at, created_at FROM refresh_tokens
WHERE user_id = $1
  AND (
      $2::timestamptz IS NULL
      OR (created_at, id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListRefreshTokensByUserParams struct {
	UserID          uuid.UUID          `json:"user_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        *uuid.UUID         `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

func (q *Queries) ListRefreshTokensByUser(ctx context.Context, arg ListRefreshTokensByUserParams) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, listRefreshTokensByUser,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefreshToken{}
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FamilyID,
			&i.TokenHash,
			&i.DeviceID,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :execrows
UPDATE refresh_tokens
SET revoked_at = $1, last_used_at = $1
WHERE id = $2 AND revoked_at IS NULL
`

type MarkRefreshTokenUsedParams struct {
	UsedAt pgtype.Timestamptz `json:"used_at"`
	ID     uuid.UUID          `json:"id"`
}

func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, arg MarkRefreshTokenUsedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRefreshTokenUsed, arg.UsedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshFamily = `-- name: RevokeRefreshFamily :execrows
UPDATE refresh_tokens SET revoked_at = $1
WHERE family_id = $2 AND revoked_at IS NULL
`

type RevokeRefreshFamilyParams struct {
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	FamilyID  uuid.UUID          `json:"family_id"`
}

func (q *Queries) RevokeRefreshFamily(ctx context.Context, arg RevokeRefreshFamilyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshFamily, arg.RevokedAt, arg.FamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserRefreshTokens = `-- name: RevokeUserRefreshTokens :execrows
UPDATE refresh_tokens SET revoked_at = $1
WHERE user_id = $2 AND revoked_at IS NULL
`

type RevokeUserRefreshTokensParams struct {
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	UserID    uuid.UUID          `json:"user_id"`
}

func (q *Queries) RevokeUserRefreshTokens(ctx context.Context, arg RevokeUserRefreshTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserRefreshTokens, arg.RevokedAt, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
