// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: summaries.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSummary = `-- name: CreateSummary :one
INSERT INTO summaries (meeting_id, template_id, language, markdown, model, action_items)
SELECT $1, $2, $3, $4,
       $5, $6
FROM meetings
WHERE meetings.id = $1 AND meetings.workspace_id = $7
RETURNING id, meeting_id, template_id, language, markdown, model, action_items, created_at
`

type CreateSummaryParams struct {
	MeetingID   uuid.UUID `json:"meeting_id"`
	TemplateID  *string   `json:"template_id"`
	Language    string    `json:"language"`
	Markdown    string    `json:"markdown"`
	Model       string    `json:"model"`
	ActionItems []byte    `json:"action_items"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) CreateSummary(ctx context.Context, arg CreateSummaryParams) (Summary, error) {
	row := q.db.QueryRow(ctx, createSummary,
		arg.MeetingID,
		arg.TemplateID,
		arg.Language,
		arg.Markdown,
		arg.Model,
		arg.ActionItems,
		arg.WorkspaceID,
	)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.TemplateID,
		&i.Language,
		&i.Markdown,
		&i.Model,
		&i.ActionItems,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSummary = `-- name: DeleteSummary :execrows
DELETE FROM summaries
USING meetings
WHERE summaries.meeting_id = meetings.id
  AND summaries.id = $1
  AND meetings.workspace_id = $2
`

type DeleteSummaryParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteSummary(ctx context.Context, arg DeleteSummaryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSummary, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSummary = `-- name: GetSummary :one
SELECT summaries.id, summaries.meeting_id, summaries.template_id, summaries.language, summaries.markdown, summaries.model, summaries.action_items, summaries.created_at FROM summaries
JOIN meetings ON meetings.id = summaries.meeting_id
WHERE summaries.id = $1 AND meetings.workspace_id = $2
`

type GetSummaryParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetSummary(ctx context.Context, arg GetSummaryParams) (Summary, error) {
	row := q.db.QueryRow(ctx, getSummary, arg.ID, arg.WorkspaceID)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.TemplateID,
		&i.Language,
		&i.Markdown,
		&i.Model,
		&i.ActionItems,
		&i.CreatedAt,
	)
	return i, err
}

const listSummariesByWorkspace = `-- name: ListSummariesByWorkspace :many
SELECT summaries.id, summaries.meeting_id, summaries.template_id, summaries.language, summaries.markdown, summaries.model, summaries.action_items, summaries.created_at FROM summaries
JOIN meetings ON meetings.id = summaries.meeting_id
WHERE meetings.workspace_id = $1
  AND ($2::uuid IS NULL OR summaries.meeting_id = $2::uuid)
  AND (
      $3::timestamptz IS NULL
      OR (summaries.created_at, summaries.id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY summaries.created_at DESC, summaries.id DESC
LIMIT $5
`

type ListSummariesByWorkspaceParams struct {
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	MeetingID       *uuid.UUID         `json:"meeting_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        *uuid.UUID         `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

func (q *Queries) ListSummariesByWorkspace(ctx context.Context, arg ListSummariesByWorkspaceParams) ([]Summary, error) {
	rows, err := q.db.Query(ctx, listSummariesByWorkspace,
		arg.WorkspaceID,
		arg.MeetingID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Summary{}
	for rows.Next() {
		var i Summary
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.TemplateID,
			&i.Language,
			&i.Markdown,
			&i.Model,
			&i.ActionItems,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSummary = `-- name: UpdateSummary :one
UPDATE summaries SET
    template_id = COALESCE($1, template_id),
    language = COALESCE($2, language),
    markdown = COALESCE($3, markdown),
    model = COALESCE($4, model),
    action_items = COALESCE($5, action_items)
FROM meetings
WHERE summaries.meeting_id = meetings.id
  AND summaries.id = $6
  AND meetings.workspace_id = $7
RETURNING summaries.id, summaries.meeting_id, summaries.template_id, summaries.language, summaries.markdown, summaries.model, summaries.action_items, summaries.created_at
`

type UpdateSummaryParams struct {
	TemplateID  *string   `json:"template_id"`
	Language    *string   `json:"language"`
	Markdown    *string   `json:"markdown"`
	Model       *string   `json:"model"`
	ActionItems []byte    `json:"action_items"`
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateSummary(ctx context.Context, arg UpdateSummaryParams) (Summary, error) {
	row := q.db.QueryRow(ctx, updateSummary,
		arg.TemplateID,
		arg.Language,
		arg.Markdown,
		arg.Model,
		arg.ActionItems,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.TemplateID,
		&i.Language,
		&i.Markdown,
		&i.Model,
		&i.ActionItems,
		&i.CreatedAt,
	)
	return i, err
}
