// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transcript_segments.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createTranscriptSegment = `-- name: CreateTranscriptSegment :one
INSERT INTO transcript_segments (meeting_id, seq, speaker, start_s, end_s, text, embedding)
SELECT $1, $2, $3, $4,
       $5, $6, $7::vector
FROM meetings
WHERE meetings.id = $1 AND meetings.workspace_id = $8
RETURNING id, meeting_id, seq, speaker, start_s, end_s, text, embedding::text, created_at
`

type CreateTranscriptSegmentParams struct {
	MeetingID   uuid.UUID        `json:"meeting_id"`
	Seq         int32            `json:"seq"`
	Speaker     *string          `json:"speaker"`
	StartS      float64          `json:"start_s"`
	EndS        float64          `json:"end_s"`
	Text        string           `json:"text"`
	Embedding   *pgvector.Vector `json:"embedding"`
	WorkspaceID uuid.UUID        `json:"workspace_id"`
}

type CreateTranscriptSegmentRow struct {
	ID        uuid.UUID          `json:"id"`
	MeetingID uuid.UUID          `json:"meeting_id"`
	Seq       int32              `json:"seq"`
	Speaker   *string            `json:"speaker"`
	StartS    float64            `json:"start_s"`
	EndS      float64            `json:"end_s"`
	Text      string             `json:"text"`
	Embedding string             `json:"embedding"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateTranscriptSegment(ctx context.Context, arg CreateTranscriptSegmentParams) (CreateTranscriptSegmentRow, error) {
	row := q.db.QueryRow(ctx, createTranscriptSegment,
		arg.MeetingID,
		arg.Seq,
		arg.Speaker,
		arg.StartS,
		arg.EndS,
		arg.Text,
		arg.Embedding,
		arg.WorkspaceID,
	)
	var i CreateTranscriptSegmentRow
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.Seq,
		&i.Speaker,
		&i.StartS,
		&i.EndS,
		&i.Text,
		&i.Embedding,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTranscriptSegment = `-- name: DeleteTranscriptSegment :execrows
DELETE FROM transcript_segments
USING meetings
WHERE transcript_segments.meeting_id = meetings.id
  AND transcript_segments.id = $1
  AND meetings.workspace_id = $2
`

type DeleteTranscriptSegmentParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteTranscriptSegment(ctx context.Context, arg DeleteTranscriptSegmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTranscriptSegment, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTranscriptSegment = `-- name: GetTranscriptSegment :one
SELECT transcript_segments.id, transcript_segments.meeting_id, transcript_segments.seq,
       transcript_segments.speaker, transcript_segments.start_s, transcript_segments.end_s,
       transcript_segments.text, transcript_segments.embedding::text, transcript_segments.created_at
FROM transcript_segments
JOIN meetings ON meetings.id = transcript_segments.meeting_id
WHERE transcript_segments.id = $1 AND meetings.workspace_id = $2
`

type GetTranscriptSegmentParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type GetTranscriptSegmentRow struct {
	ID                          uuid.UUID          `json:"id"`
	MeetingID                   uuid.UUID          `json:"meeting_id"`
	Seq                         int32              `json:"seq"`
	Speaker                     *string            `json:"speaker"`
	StartS                      float64            `json:"start_s"`
	EndS                        float64            `json:"end_s"`
	Text                        string             `json:"text"`
	TranscriptSegmentsEmbedding string             `json:"transcript_segments_embedding"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetTranscriptSegment(ctx context.Context, arg GetTranscriptSegmentParams) (GetTranscriptSegmentRow, error) {
	row := q.db.QueryRow(ctx, getTranscriptSegment, arg.ID, arg.WorkspaceID)
	var i GetTranscriptSegmentRow
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.Seq,
		&i.Speaker,
		&i.StartS,
		&i.EndS,
		&i.Text,
		&i.TranscriptSegmentsEmbedding,
		&i.CreatedAt,
	)
	return i, err
}

const listTranscriptSegmentsByWorkspace = `-- name: ListTranscriptSegmentsByWorkspace :many
SELECT transcript_segments.id, transcript_segments.meeting_id, transcript_segments.seq,
       transcript_segments.speaker, transcript_segments.start_s, transcript_segments.end_s,
       transcript_segments.text, transcript_segments.embedding::text, transcript_segments.created_at
FROM transcript_segments
JOIN meetings ON meetings.id = transcript_segments.meeting_id
WHERE meetings.workspace_id = $1
  AND ($2::uuid IS NULL OR transcript_segments.meeting_id = $2::uuid)
  AND (
      $3::timestamptz IS NULL
      OR (transcript_segments.created_at, transcript_segments.id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY transcript_segments.created_at DESC, transcript_segments.id DESC
LIMIT $5
`

type ListTranscriptSegmentsByWorkspaceParams struct {
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	MeetingID       *uuid.UUID         `json:"meeting_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        *uuid.UUID         `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

type ListTranscriptSegmentsByWorkspaceRow struct {
	ID                          uuid.UUID          `json:"id"`
	MeetingID                   uuid.UUID          `json:"meeting_id"`
	Seq                         int32              `json:"seq"`
	Speaker                     *string            `json:"speaker"`
	StartS                      float64            `json:"start_s"`
	EndS                        float64            `json:"end_s"`
	Text                        string             `json:"text"`
	TranscriptSegmentsEmbedding string             `json:"transcript_segments_embedding"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListTranscriptSegmentsByWorkspace(ctx context.Context, arg ListTranscriptSegmentsByWorkspaceParams) ([]ListTranscriptSegmentsByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listTranscriptSegmentsByWorkspace,
		arg.WorkspaceID,
		arg.MeetingID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTranscriptSegmentsByWorkspaceRow{}
	for rows.Next() {
		var i ListTranscriptSegmentsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.Seq,
			&i.Speaker,
			&i.StartS,
			&i.EndS,
			&i.Text,
			&i.TranscriptSegmentsEmbedding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTranscriptSegment = `-- name: UpdateTranscriptSegment :one
UPDATE transcript_segments SET
    speaker = COALESCE($1, speaker),
    start_s = COALESCE($2, start_s),
    end_s = COALESCE($3, end_s),
    text = COALESCE($4, text),
    embedding = COALESCE($5::vector, embedding)
FROM meetings
WHERE transcript_segments.meeting_id = meetings.id
  AND transcript_segments.id = $6
  AND meetings.workspace_id = $7
RETURNING transcript_segments.id, transcript_segments.meeting_id, transcript_segments.seq,
       transcript_segments.speaker, transcript_segments.start_s, transcript_segments.end_s,
       transcript_segments.text, transcript_segments.embedding::text, transcript_segments.created_at
`

type UpdateTranscriptSegmentParams struct {
	Speaker     *string          `json:"speaker"`
	StartS      *float64         `json:"start_s"`
	EndS        *float64         `json:"end_s"`
	Text        *string          `json:"text"`
	Embedding   *pgvector.Vector `json:"embedding"`
	ID          uuid.UUID        `json:"id"`
	WorkspaceID uuid.UUID        `json:"workspace_id"`
}

type UpdateTranscriptSegmentRow struct {
	ID                          uuid.UUID          `json:"id"`
	MeetingID                   uuid.UUID          `json:"meeting_id"`
	Seq                         int32              `json:"seq"`
	Speaker                     *string            `json:"speaker"`
	StartS                      float64            `json:"start_s"`
	EndS                        float64            `json:"end_s"`
	Text                        string             `json:"text"`
	TranscriptSegmentsEmbedding string             `json:"transcript_segments_embedding"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateTranscriptSegment(ctx context.Context, arg UpdateTranscriptSegmentParams) (UpdateTranscriptSegmentRow, error) {
	row := q.db.QueryRow(ctx, updateTranscriptSegment,
		arg.Speaker,
		arg.StartS,
		arg.EndS,
		arg.Text,
		arg.Embedding,
		arg.ID,
		arg.WorkspaceID,
	)
	var i UpdateTranscriptSegmentRow
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.Seq,
		&i.Speaker,
		&i.StartS,
		&i.EndS,
		&i.Text,
		&i.TranscriptSegmentsEmbedding,
		&i.CreatedAt,
	)
	return i, err
}
