// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (name, slug, bot_name, retention_days)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, bot_name, retention_days, created_at
`

type CreateWorkspaceParams struct {
	Name          string `json:"name"`
	Slug          string `json:"slug"`
	BotName       string `json:"bot_name"`
	RetentionDays int32  `json:"retention_days"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.Name,
		arg.Slug,
		arg.BotName,
		arg.RetentionDays,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.BotName,
		&i.RetentionDays,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :execrows
DELETE FROM workspaces WHERE id = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkspace, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, slug, bot_name, retention_days, created_at FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.BotName,
		&i.RetentionDays,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceBySlug = `-- name: GetWorkspaceBySlug :one
SELECT id, name, slug, bot_name, retention_days, created_at FROM workspaces WHERE slug = $1
`

func (q *Queries) GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBySlug, slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.BotName,
		&i.RetentionDays,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkspacesByUser = `-- name: ListWorkspacesByUser :many
SELECT workspaces.id, workspaces.name, workspaces.slug, workspaces.bot_name, workspaces.retention_days, workspaces.created_at FROM workspaces
JOIN memberships ON memberships.workspace_id = workspaces.id
WHERE memberships.user_id = $1
  AND (
      $2::timestamptz IS NULL
      OR (workspaces.created_at, workspaces.id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY workspaces.created_at DESC, workspaces.id DESC
LIMIT $4
`

type ListWorkspacesByUserParams struct {
	UserID          uuid.UUID          `json:"user_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        *uuid.UUID         `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

func (q *Queries) ListWorkspacesByUser(ctx context.Context, arg ListWorkspacesByUserParams) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByUser,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.BotName,
			&i.RetentionDays,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces SET
    name = COALESCE($1, name),
    slug = COALESCE($2, slug),
    bot_name = COALESCE($3, bot_name),
    retention_days = COALESCE($4, retention_days)
WHERE id = $5
RETURNING id, name, slug, bot_name, retention_days, created_at
`

type UpdateWorkspaceParams struct {
	Name          *string   `json:"name"`
	Slug          *string   `json:"slug"`
	BotName       *string   `json:"bot_name"`
	RetentionDays *int32    `json:"retention_days"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace,
		arg.Name,
		arg.Slug,
		arg.BotName,
		arg.RetentionDays,
		arg.ID,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.BotName,
		&i.RetentionDays,
		&i.CreatedAt,
	)
	return i, err
}
